[general]
static=yes
writeprotect=yes
clearglobalvars=no

[globals]

[from-internal]
exten => 1001,1,NoOp(Internal call to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},45)
 same => n,Hangup()

exten => 1002,1,NoOp(Internal call to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},45)
 same => n,Hangup()

exten => _10XX,1,NoOp(Internal call to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},45)
 same => n,Hangup()
